name: Proto Compiler Action
description: 'A GitHub Action to compile protobuf files for golang and javascript/typescript'
inputs:
  commit_message:
    description: 'Commit message for the changes'
    required: true
  command:
    description: 'Custom protoc command to run inside the Docker container with this repository mounted to the Working Directory /app'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: |
        docker pull ghcr.io/valentin-kaiser/docker-proto-compiler:latest
        docker run --rm -v ${{ github.workspace }}:/app ghcr.io/valentin-kaiser/docker-proto-compiler:latest '${{ inputs.command }}'
      shell: bash
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff
        git add -A
        git commit -m "${{ inputs.commit_message }}" || echo "No changes to commit"
        git push
      shell: bash