name: Compile and Commit Proto with Action

on: [push]

jobs:
  compile-and-commit-proto:
    runs-on: ubuntu-latest

    steps:
    - name: Use custom proto compiler and committer action
      uses: valentin-kaiser/protocdock@master
      with:
        command: 'cd proto && mkdir -p ./gen/ && protoc generic.proto --plugin=ts-protoc-gen=$PROTOC_GEN_TS_PATH --go_out=./gen/ --go-grpc_out=./gen/ --js_out="import_style=commonjs,binary:./gen/" --grpc-web_out="import_style=typescript,mode=grpcweb:./gen/" --proto_path=/app/proto'
        commit_message: '[GEN] Updated compiled proto definitions'
