name: ProtocDock

on:
  push:
    paths:
      - 'proto/**' # When the proto files are updated we want to recompile them
      - 'Dockerfile' # When the Dockerfile is updated we want to recompile the proto files with the new action

permissions:
  contents: write
  pull-requests: write

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: ProtocDock Compile
      uses: valentin-kaiser/protocdock@master
      with:
        command: 'cd proto && rm -r ./gen/ && mkdir -p ./gen/ && protoc generic.proto --plugin=ts-protoc-gen=$PROTOC_GEN_TS_PATH --go_out=./gen/ --go-grpc_out=./gen/ --js_out="import_style=commonjs,binary:./gen/" --grpc-web_out="import_style=typescript,mode=grpcweb:./gen/" --proto_path=/app/proto'
        commit_message: '[GEN] Updated compiled proto definitions'
