name: Compile and Commit Proto with Action

on: [push]

jobs:
  compile-and-commit-proto:
    runs-on: ubuntu-latest

    steps:
    - name: Use custom proto compiler and committer action
      uses: Valentin-Kaiser/docker-proto-compiler@main
      with:
        command: 'cd proto && make'
        commit_message: '[GEN] Updated compiled proto definitions'
